# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Circle, Wedge
import matplotlib.patches as mpatches

# Simulation parameters
n_throws = 8000
board_radius = 10

# Generate random dart throws
x = np.random.uniform(-board_radius, board_radius, n_throws)
y = np.random.uniform(-board_radius, board_radius, n_throws)
distances = np.sqrt(x**2 + y**2)

# Dartboard zones
bullseye_radius = 0.6
inner_bull_radius = 1.2
triple_inner = 6.3
triple_outer = 7.0
double_inner = 9.3
double_outer = 10.0

# Classify hits
bullseye_hits = distances <= bullseye_radius
inner_bull_hits = (distances > bullseye_radius) & (distances <= inner_bull_radius)
board_hits = distances <= board_radius

# Create figure with dark theme
fig, ax = plt.subplots(figsize=(12, 12), facecolor='#0d1117')
ax.set_facecolor('#0d1117')

# Draw dartboard with alternating segments
n_segments = 20
colors_outer = ['#1a1a1a', '#f0f0f0']
colors_inner = ['#8b0000', '#2d5c2d']

# Outer segments
for i in range(n_segments):
    angle = i * 360 / n_segments
    wedge = Wedge((0, 0), board_radius, angle, angle + 360/n_segments,
                  facecolor=colors_outer[i % 2], edgecolor='#333', linewidth=0.5, alpha=0.4)
    ax.add_patch(wedge)

# Double ring
for i in range(n_segments):
    angle = i * 360 / n_segments
    wedge = Wedge((0, 0), double_outer, angle, angle + 360/n_segments,
                  width=double_outer-double_inner,
                  facecolor=colors_outer[i % 2], edgecolor='#666', linewidth=0.3, alpha=0.9)
    ax.add_patch(wedge)

# Triple ring
for i in range(n_segments):
    angle = i * 360 / n_segments
    wedge = Wedge((0, 0), triple_outer, angle, angle + 360/n_segments,
                  width=triple_outer-triple_inner,
                  facecolor=colors_inner[i % 2], edgecolor='#666', linewidth=0.3, alpha=0.9)
    ax.add_patch(wedge)

# Center circles
circles_data = [
    (inner_bull_radius, '#2ecc71', 2.5),
    (bullseye_radius, '#e74c3c', 3),
]

for radius, color, lw in circles_data:
    circle = Circle((0, 0), radius, color=color, fill=True,
                   linewidth=lw, edgecolor='#ecf0f1', alpha=0.95, zorder=5)
    ax.add_patch(circle)

# Plot darts with gradient effect
regular_mask = board_hits & ~bullseye_hits & ~inner_bull_hits
miss_mask = ~board_hits

# Misses (outside board)
ax.scatter(x[miss_mask], y[miss_mask], c='#596e79', s=2, alpha=0.3, zorder=8)

# Regular hits
ax.scatter(x[regular_mask], y[regular_mask], c='#3498db', s=4, alpha=0.5,
          edgecolors='#2980b9', linewidths=0.3, zorder=10)

# Inner bull
ax.scatter(x[inner_bull_hits], y[inner_bull_hits], c='#f39c12', s=15, alpha=0.85,
          edgecolors='#e67e22', linewidths=0.5, zorder=11)

# Bullseye
ax.scatter(x[bullseye_hits], y[bullseye_hits], c='#00ff88', s=25, alpha=0.95,
          edgecolors='#00cc66', linewidths=0.8, zorder=12, marker='*')

# Statistics
hits_on_board = np.sum(board_hits)
hits_bullseye = np.sum(bullseye_hits)
hits_inner = np.sum(inner_bull_hits)
accuracy = (hits_on_board / n_throws) * 100

# Elegant info box
info_text = f'MONTE CARLO SIMULATION\n{"─" * 28}\n'
info_text += f'Total Throws      {n_throws:,}\n'
info_text += f'Board Hits        {hits_on_board:,}\n'
info_text += f'Inner Bull        {hits_inner}\n'
info_text += f'Bullseye          {hits_bullseye}\n'
info_text += f'Accuracy          {accuracy:.1f}%'

ax.text(-9.8, 9.8, info_text, fontsize=10, color='#ecf0f1',
        verticalalignment='top', family='monospace', fontweight='bold',
        bbox=dict(boxstyle='round,pad=0.8', facecolor='#1c2833',
                 alpha=0.9, edgecolor='#3498db', linewidth=2))

# Modern legend
legend_elements = [
    mpatches.Patch(color='#3498db', label='Board Hits', alpha=0.7),
    mpatches.Patch(color='#f39c12', label='Inner Bull', alpha=0.85),
    mpatches.Patch(color='#00ff88', label='Bullseye ★', alpha=0.95),
    mpatches.Patch(color='#596e79', label='Misses', alpha=0.4),
]
legend = ax.legend(handles=legend_elements, loc='upper right',
                  facecolor='#1c2833', edgecolor='#3498db',
                  fontsize=11, labelcolor='#ecf0f1',
                  framealpha=0.9, title='LEGEND', title_fontsize=11)
legend.get_title().set_color('#ecf0f1')
legend.get_title().set_weight('bold')
legend.get_frame().set_linewidth(2)

# Formatting
ax.set_xlim(-11.5, 11.5)
ax.set_ylim(-11.5, 11.5)
ax.set_aspect('equal')
ax.set_title('DARTBOARD MONTE CARLO VISUALIZATION',
            color='#ecf0f1', fontsize=18, fontweight='bold',
            pad=25, family='sans-serif')

# Clean axes
ax.spines['top'].set_color('#34495e')
ax.spines['bottom'].set_color('#34495e')
ax.spines['left'].set_color('#34495e')
ax.spines['right'].set_color('#34495e')
ax.tick_params(colors='#7f8c8d', labelsize=9)
ax.grid(True, alpha=0.15, color='#34495e', linestyle='--', linewidth=0.5)
ax.set_xlabel('X Coordinate', color='#95a5a6', fontsize=11, fontweight='bold')
ax.set_ylabel('Y Coordinate', color='#95a5a6', fontsize=11, fontweight='bold')

plt.tight_layout()
plt.show()